"""adding followers2

Revision ID: 5982a8a2b0bc
Revises: 79847644176d
Create Date: 2018-12-06 00:23:32.466566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5982a8a2b0bc'
down_revision = '79847644176d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
